${pojo.getPackageDeclaration()}
<#--// Generated ${date} by Hibernate Tools ${version}-->

<#assign classbody>
/**
${pojo.getClassJavaDoc(pojo.getDeclarationName() + " generated by hbm2java", 0)}
 */
@${pojo.importType("org.springframework.stereotype.Repository")}
public interface ${pojo.getDeclarationName()} extends ${pojo.importType("org.springframework.data.jpa.repository.JpaRepository")}<${pojo.importType(pojo.getEntityClass())}, ${pojo.getEntityIdClass()}>{

}
</#assign>

${pojo.generateImports()}
${classbody}
